CREATE TABLE `user_devices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`os` varchar(64),
	`osVersion` varchar(32),
	`browser` varchar(64),
	`browserVersion` varchar(32),
	`deviceModel` varchar(128),
	`deviceType` varchar(32),
	`ip` varchar(64),
	`ipRegion` varchar(128),
	`screenWidth` int,
	`screenHeight` int,
	`language` varchar(16),
	`timezone` varchar(64),
	`fingerprint` varchar(256),
	`userAgent` text,
	`platform` varchar(32),
	`isOnline` boolean NOT NULL DEFAULT false,
	`lastActiveAt` timestamp NOT NULL DEFAULT (now()),
	`firstSeenAt` timestamp NOT NULL DEFAULT (now()),
	`loginCount` int NOT NULL DEFAULT 1,
	CONSTRAINT `user_devices_id` PRIMARY KEY(`id`)
);
